removing Singletons, and just creating new objects when needed
royboy789/gutenberg-object-plugin pull request #11
Opened 2018-07-12 04:08 UTC by royboy789

Fix for #5 

@tomjn - let me know what you think.

2018-07-12 13:59 UTC, tomjn requested changes
I'd also recommend moving stuff out of the constructor to a dedicated `run` function. This way creating the object and using the object are separate tasks.

This also means in the root file we get a nice 3 step process:
 - load the class files
 - create and assemble the program from objects like lego
 - tell it we're ready to run and go do things

2018-07-12 13:59 UTC, tomjn commented on GutenbergObjectPlugin.php
> -class GutenbergObjectPlugin {
I would keep the gutenberg plugin object, it provides structure and gives all the other objects somewhere to live. Pass the other objects in via the constructor and store them as member variables

2018-07-12 13:59 UTC, tomjn commented on src/Hooks.php
> +			$this->API = new API();
This leads to multiple API objects, instead eliminate this entire check, and change the constructor

2018-07-12 13:59 UTC, tomjn commented on src/Hooks.php
>  	public function __construct() {
Lets use dependency injection by changing the constructor, this object requires an `API` object to do it's work, so lets make it ask for one when it gets created:

```php
public function __construct( API $api ) {
    $this->api = $api;
}
```

Now we don't need to check if api is set, if it isn't set the constructor will throw an error thanks to the type hinting

2018-07-12 13:59 UTC, tomjn commented on src/Hooks.php
>  	private $API;
Lets keep variables lowercase, and use uppercase for the Class names instead

2018-07-12 14:00 UTC, tomjn commented on GutenbergObjectPlugin.php
> -class GutenbergObjectPlugin {
Keep in mind though that this object should take all the other objects in as dependencies, and it shouldn't do anything itself that isn't a method call of its children.

2018-07-12 14:05 UTC, tomjn commented
The final bootstrap might look something like this:

```php

// definitions
namespace GutenbergArray;

define( 'GutesArraySaveUrl', plugin_dir_url( __FILE__ ) );
define( 'GutesArrayPluginFile', __FILE__ );

// load classes
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
	require_once 'vendor/autoload.php';
}

// construct plugin
$api = new API();
$hooks = new Hooks( $api );
$scripts = new Scripts();
$database = new Database();
$plugin = new GutenbergObjectPlugin( $hooks, $scripts, $database );

// run plugin, register hooks, etc
$plugin->run();
```

Additionally, `GutesArraySaveUrl` and `GutesArrayPluginFile` could be passed in via the constructor too, preventing the need for a `define`, and letting you reuse the class.

If the plugin got bigger, you could swap classes out for interfaces and build different implementations, e.g. `TestDatabase` or `MemcachedDatabase` and as long as all the typehints used the interfaces they could be interchanged. But I don't think that's needed here

2018-07-12 20:33 UTC, royboy789 commented
@tomjn think I got through all of your notes, and did some more refactoring (namespace was bugging me).

2018-07-13 06:37 UTC, merged

2018-07-13 11:43 UTC, tomjn commented
Looks good, my only change would have been to move the top level class to its own file and pass in the  `__FILE__` etc in the constructor so they aren't needed as static variables